[package]
name          = "rustls-connector"
version       = "0.9.0" # remember to update html_root_url
authors       = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition       = "2018"
description   = "Connector similar to openssl or native-tls for rustls"
repository    = "https://github.com/Keruspe/rustls-connector"
documentation = "https://docs.rs/rustls-connector"
keywords      = ["tls", "rustls"]
categories    = ["network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "rustls_connector"

[features]
default                 = []
dangerous_configuration = [ "rustls/dangerous_configuration" ]
native_certs            = [ "rustls-native-certs" ]
quic                    = [ "rustls/quic" ]

[dependencies]
log          = "^0.4"
rustls       = "^0.17"
webpki       = "^0.21"
webpki-roots = "^0.19"

[dependencies.rustls-native-certs]
version  = "^0.3"
optional = true

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "Keruspe/rustls-connector" }
appveyor  = { repository = "Keruspe/rustls-connector" }
